package com.shanebeestudios.mcdeop.processor.mache;

import java.util.ArrayList;
import java.util.List;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.jetbrains.annotations.Nullable;

/**
 * Reads elements out of the two Maven documents McDeob needs: {@code maven-metadata.xml} and a POM's packaging.
 *
 * <p>A scanner rather than a full XML parser, because both documents are generated by Maven repositories with a
 * fixed shape, and avoiding {@code javax.xml} keeps the native image free of the JAXP provider lookup that would
 * otherwise have to be configured.
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
final class XmlElements {

    /**
     * Returns the text of the first {@code <tag>…</tag>}.
     *
     * @param source the document to scan
     * @param tag the element name, without angle brackets
     * @return the trimmed content, or {@code null} if the element is absent
     */
    static @Nullable String first(final String source, final String tag) {
        final String open = '<' + tag + '>';
        final String close = "</" + tag + '>';

        final int start = source.indexOf(open);
        if (start < 0) {
            return null;
        }
        final int end = source.indexOf(close, start + open.length());
        if (end < 0) {
            return null;
        }
        return source.substring(start + open.length(), end).trim();
    }

    /**
     * Returns the text of every {@code <tag>…</tag>}, in document order.
     *
     * @param source the document to scan
     * @param tag the element name, without angle brackets
     * @return the trimmed contents, empty if the element never occurs
     */
    static List<String> all(final String source, final String tag) {
        final String open = '<' + tag + '>';
        final String close = "</" + tag + '>';

        final List<String> values = new ArrayList<>();
        int cursor = 0;
        while (true) {
            final int start = source.indexOf(open, cursor);
            if (start < 0) {
                return values;
            }
            final int end = source.indexOf(close, start + open.length());
            if (end < 0) {
                return values;
            }

            values.add(source.substring(start + open.length(), end).trim());
            cursor = end + close.length();
        }
    }
}
