name: Update Files

on:
    pull_request:
        branches: [ master ]

permissions: { }

jobs:
    auto-format:
        name: Auto-Format
        runs-on: ubuntu-latest
        steps:
            -   name: Harden Runner
                uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
                with:
                    egress-policy: audit

            -   name: Auto-Format Code
                uses: TimSchoenle/actions/actions/java-gradle/auto-spotless@e110c51015a7f4208ef6ef67c929147987f7bb68 # actions-java-gradle-auto-spotless-v1.1.2
                with:
                    java_version: '25'
                    bot_private_key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
                    bot_app_id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
