name: Update Files

on:
    pull_request:
        branches: [ master ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: { }

jobs:
    auto-format:
        name: Auto-Format
        runs-on: ubuntu-latest
        steps:
            -   name: Harden Runner
                uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
                with:
                    egress-policy: audit

            -   name: Auto-Format Code
                uses: TimSchoenle/actions/actions/java-gradle/auto-spotless@e765cff1a4b68452e074f186bb8cceb8e92afea3 # actions-java-gradle-auto-spotless-v1.1.4
                with:
                    java_version: '25'
                    bot_private_key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
                    bot_app_id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
