name: Update Files

on:
    pull_request:
        branches: [ master ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: { }

jobs:
    auto-format:
        name: Auto-Format
        runs-on: ubuntu-latest
        steps:
            -   name: Harden Runner
                uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
                with:
                    egress-policy: audit

            -   name: Auto-Format Code
                uses: TimSchoenle/actions/actions/java-gradle/auto-spotless@b1209011d0c4d276451024499e1b408e5e8a313b # tag=actions-java-gradle-auto-spotless-v1.1.15
                with:
                    java_version: '25'
                    bot_private_key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
                    bot_app_id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
